
package no.clarino.pid.nb.urn.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IdTestService", targetNamespace = "http://nb.no/idservice/v1.0/", wsdlLocation = "http://www.nb.no/idtjeneste-test/ws?wsdl")
public class IdTestService_Service
    extends Service
{

    private final static URL IDSERVICE_WSDL_LOCATION;
    private final static WebServiceException IDSERVICE_EXCEPTION;
    private final static QName IDSERVICE_QNAME = new QName("http://nb.no/idservice/v1.0/", "IdService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.nb.no/idtjeneste-test/ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDSERVICE_WSDL_LOCATION = url;
        IDSERVICE_EXCEPTION = e;
    }

    public IdTestService_Service() {
        super(__getWsdlLocation(), IDSERVICE_QNAME);
    }

    public IdTestService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDSERVICE_QNAME, features);
    }

    public IdTestService_Service(URL wsdlLocation) {
        super(wsdlLocation, IDSERVICE_QNAME);
    }

    public IdTestService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDSERVICE_QNAME, features);
    }

    public IdTestService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdTestService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IdTestService
     */
    @WebEndpoint(name = "IdTestServiceSOAP11Port")
    public IdTestService getIdTestServiceSOAP11Port() {
        return super.getPort(new QName("http://nb.no/idservice/v1.0/", "IdTestServiceSOAP11Port"), IdTestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdTestService
     */
    @WebEndpoint(name = "IdTestServiceSOAP11Port")
    public IdTestService getIdTestServiceSOAP11Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://nb.no/idservice/v1.0/", "IdTestServiceSOAP11Port"), IdTestService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDSERVICE_EXCEPTION!= null) {
            throw IDSERVICE_EXCEPTION;
        }
        return IDSERVICE_WSDL_LOCATION;
    }

}
